Added optional '-f' argument to allow the user to specify which framework they would like to use. As of right now I only have plans of adding support for Bootstrap, Materialize, and Tailwindcss. Example usage: '-f bootstrap'

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -13,6 +13,27 @@ while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symli
 done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
+while getopts "f:" opt; do
+  case $opt in
+    f) framework="$OPTARG"
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
+if [ -z "$framework" ]; then
+  echo No framework selected. Generating Core JS-Gulp Project without a framework.
+elif [ "$framework" == "bootstrap" ]; then
+  echo Generating Core JS-Gulp Project with Bootstrap!
+elif [ "$framework" == "materialize" ]; then
+  echo Generating Core JS-Gulp Project with Materialize!
+elif [ "$framework" == "tailwind" ]; then
+  echo Generating Core JS-Gulp Project with Tailwind!
+else
+  echo "Sorry $framework is not a valid option!" >&2
+fi
+
 echo @@@@@@Starting project boilerplate@@@@@@
 
 read -p "What will you call this project? " PROJECT_NAME
@@ -74,25 +95,35 @@ echo // This file was automatically generated by js-gulp-gen $(date +'%a %b %d %
 
 cp $DIR/src/media/js_gulp_gen_logo.png assets/images/js_gulp_gen_logo.png
 
-echo /* This file was automatically generated by js-gulp-gen $(date +'%a %b %d %Y @ %r') */ > assets/css/tailwind.css
-echo "@tailwind preflight; @tailwind utilities;" > assets/css/tailwind.css
-
 echo Initializing npm, after project setup you may edit your package.json as you see fit.
 npm init -y
 
 echo Initializing bower, after project setup you may edit your bower.json as you see fit.
 yes '' | bower init
 
-echo Installing dev npm packages
+if [ -z "$framework" ]; then
+  echo Coming Soon!
+elif [ "$framework" == "bootstrap" ]; then
+  echo Coming Soon!
+elif [ "$framework" == "materialize" ]; then
+  echo Coming Soon!
+elif [ "$framework" == "tailwind" ]; then
+  echo /* This file was automatically generated by js-gulp-gen $(date +'%a %b %d %Y @ %r') */ > assets/css/tailwind.css
+  echo "@tailwind preflight; @tailwind utilities;" > assets/css/tailwind.css
 
-npm install autoprefixer babel-core babel-preset-env babelify bower-files browser-sync browserify del gulp gulp-clean-css gulp-concat gulp-imagemin gulp-jshint gulp-postcss gulp-uglify gulp-util jasmine@2.9.0 jasmine-core@2.9.1 jshint karma karma-browserify karma-chrome-launcher karma-cli karma-jasmine karma-jasmine-html-reporter karma-jquery tailwindcss vinyl-source-stream watchify --save-dev
+  echo Installing dev npm packages
+  npm install autoprefixer babel-core babel-preset-env babelify bower-files browser-sync browserify del gulp gulp-clean-css gulp-concat gulp-imagemin gulp-jshint gulp-postcss gulp-uglify gulp-util jasmine@2.9.0 jasmine-core@2.9.1 jshint karma karma-browserify karma-chrome-launcher karma-cli karma-jasmine karma-jasmine-html-reporter karma-jquery tailwindcss vinyl-source-stream watchify --save-dev
 
-echo Installing bower packages
-bower install jquery --save
+  echo Installing bower packages
+  bower install jquery --save
 
-echo Creating gulpfile
-echo // This file was automatically generated by js-gulp-gen $(date +'%a %b %d %Y @ %r') > gulpfile.js
-cat $DIR/src/gulpfile > gulpfile.js
+  echo Creating gulpfile
+  echo // This file was automatically generated by js-gulp-gen $(date +'%a %b %d %Y @ %r') > gulpfile.js
+  cat $DIR/src/gulpfile > gulpfile.js
+
+  echo Initializing tailwindcss
+  ./node_modules/.bin/tailwind init tailwind.js
+fi
 
 echo Creating .jshintrc
 echo "{ \"esversion\": 6 }" > .jshintrc
@@ -105,9 +136,6 @@ rm spec/support/jasmine.json
 
 echo Creating new default jasmine.json
 cat $DIR/src/jasmine > spec/support/jasmine.json
-
-echo Initializing tailwindcss
-./node_modules/.bin/tailwind init tailwind.js
 
 echo Adding sample test spec to pass karma test run
 echo // This file was automatically generated by js-gulp-gen $(date +'%a %b %d %Y @ %r') > spec/app-spec.js
